#!/usr/bin/env python3
"""Generate LUT .mem files for LUT-based STDP weight updates.

Replicates the exact arithmetic from snn_dynamic_optimized.v STDP datapath.
Each LUT stores a clamped, scaled delta value indexed by two trace values.

Potentiation LUT: indexed by {r1, o2} -> pot_shift (scaled potentiation delta)
Depression  LUT: indexed by {o1, r2} -> dep_shift (scaled depression delta)

With 4-bit traces: 16 x 16 = 256 entries, 4-bit output each.

Usage:
    python3 gen_stdp_lut.py                         # defaults (match RTL)
    python3 gen_stdp_lut.py --output-dir ../lut     # custom output dir
    python3 gen_stdp_lut.py --triplet-en 0          # pair-only mode
"""

import argparse
import os


def compute_pot_entry(r1, o2, a2_plus, a3_plus, trace_bits, dw_scale, w_max, triplet_en):
    """Compute potentiation delta for a single (r1, o2) pair.

    Mirrors RTL: pot_raw = r1 * A2_PLUS + ((r1 * o2) >> TRACE_BITS) * A3_PLUS
                 pot_shift = min(pot_raw >> DW_SCALE, W_MAX)
    """
    pot_raw = r1 * a2_plus
    if triplet_en:
        pot_raw += ((r1 * o2) >> trace_bits) * a3_plus
    pot_shift = pot_raw >> dw_scale
    if pot_shift > w_max:
        pot_shift = w_max
    return pot_shift


def compute_dep_entry(o1, r2, a2_minus, a3_minus, trace_bits, dw_scale, w_max, triplet_en):
    """Compute depression delta for a single (o1, r2) pair.

    Mirrors RTL: dep_raw = o1 * A2_MINUS + ((o1 * r2) >> TRACE_BITS) * A3_MINUS
                 dep_shift = min(dep_raw >> DW_SCALE, W_MAX)
    """
    dep_raw = o1 * a2_minus
    if triplet_en:
        dep_raw += ((o1 * r2) >> trace_bits) * a3_minus
    dep_shift = dep_raw >> dw_scale
    if dep_shift > w_max:
        dep_shift = w_max
    return dep_shift


def generate_luts(args):
    """Generate potentiation and depression LUT contents."""
    trace_max = (1 << args.trace_bits) - 1
    w_max = (1 << args.w_bits) - 1
    dw_scale = args.trace_bits - 2
    num_entries = (trace_max + 1) ** 2  # 16 x 16 = 256 for 4-bit traces

    pot_lut = []
    dep_lut = []

    for high in range(trace_max + 1):
        for low in range(trace_max + 1):
            # Potentiation: high = r1, low = o2
            pot_val = compute_pot_entry(
                high, low, args.a2_plus, args.a3_plus,
                args.trace_bits, dw_scale, w_max, args.triplet_en
            )
            pot_lut.append(pot_val)

            # Depression: high = o1, low = r2
            dep_val = compute_dep_entry(
                high, low, args.a2_minus, args.a3_minus,
                args.trace_bits, dw_scale, w_max, args.triplet_en
            )
            dep_lut.append(dep_val)

    return pot_lut, dep_lut, num_entries


def write_mem_file(filepath, lut, w_bits):
    """Write LUT contents to a .mem file in hex format (one entry per line)."""
    hex_width = (w_bits + 3) // 4  # number of hex digits
    with open(filepath, "w") as f:
        for val in lut:
            f.write(f"{val:0{hex_width}x}\n")


def write_verilog_header(filepath, pot_lut, dep_lut, w_bits):
    """Write a Verilog include file with hardcoded LUT data for synthesis."""
    hex_width = (w_bits + 3) // 4
    with open(filepath, "w") as f:
        f.write("// Auto-generated by gen_stdp_lut.py — do not edit\n")
        f.write("// Potentiation LUT: indexed by {trace1[TRACE_BITS-1:0], trace2[TRACE_BITS-1:0]}\n")
        f.write("// Depression  LUT: indexed by {trace1[TRACE_BITS-1:0], trace2[TRACE_BITS-1:0]}\n\n")

        for i, val in enumerate(pot_lut):
            f.write(f"lut_pot[{i}] = {w_bits}'h{val:0{hex_width}x}; ")
            if (i + 1) % 16 == 0:
                f.write("\n")

        f.write("\n")

        for i, val in enumerate(dep_lut):
            f.write(f"lut_dep[{i}] = {w_bits}'h{val:0{hex_width}x}; ")
            if (i + 1) % 16 == 0:
                f.write("\n")


def self_test(pot_lut, dep_lut, args):
    """Verify every LUT entry matches direct arithmetic computation."""
    trace_max = (1 << args.trace_bits) - 1
    w_max = (1 << args.w_bits) - 1
    dw_scale = args.trace_bits - 2
    errors = 0

    for r1 in range(trace_max + 1):
        for o2 in range(trace_max + 1):
            addr = r1 * (trace_max + 1) + o2
            expected = compute_pot_entry(
                r1, o2, args.a2_plus, args.a3_plus,
                args.trace_bits, dw_scale, w_max, args.triplet_en
            )
            if pot_lut[addr] != expected:
                print(f"  POT MISMATCH at r1={r1}, o2={o2}: LUT={pot_lut[addr]}, expected={expected}")
                errors += 1

    for o1 in range(trace_max + 1):
        for r2 in range(trace_max + 1):
            addr = o1 * (trace_max + 1) + r2
            expected = compute_dep_entry(
                o1, r2, args.a2_minus, args.a3_minus,
                args.trace_bits, dw_scale, w_max, args.triplet_en
            )
            if dep_lut[addr] != expected:
                print(f"  DEP MISMATCH at o1={o1}, r2={r2}: LUT={dep_lut[addr]}, expected={expected}")
                errors += 1

    return errors


def main():
    parser = argparse.ArgumentParser(description="Generate STDP LUT .mem files")
    parser.add_argument("--w-bits", type=int, default=4, help="Weight bit width (default: 4)")
    parser.add_argument("--trace-bits", type=int, default=4, help="Trace bit width (default: 4)")
    parser.add_argument("--triplet-en", type=int, default=1, help="Triplet STDP enable (default: 1)")
    parser.add_argument("--symmetric", type=int, default=0, help="Symmetric LTP/LTD (default: 0)")
    parser.add_argument("--a2-plus", type=int, default=1, help="A2_PLUS parameter (default: 1)")
    parser.add_argument("--a2-minus", type=int, default=None, help="A2_MINUS (default: A2_PLUS if symmetric, else 1)")
    parser.add_argument("--a3-plus", type=int, default=1, help="A3_PLUS parameter (default: 1)")
    parser.add_argument("--a3-minus", type=int, default=4, help="A3_MINUS parameter (default: 4)")
    parser.add_argument("--output-dir", type=str, default="../lut", help="Output directory (default: ../lut)")
    parser.add_argument("--no-test", action="store_true", help="Skip self-test")
    args = parser.parse_args()

    # Handle A2_MINUS default (mirrors RTL: SYMMETRIC ? A2_PLUS : 4'd1)
    # Note: RTL default for non-symmetric A2_MINUS is hardcoded as 4'd3 in the parameter,
    # but the actual default when SYMMETRIC=0 is A2_MINUS=1 per the parameter declaration.
    # We match the RTL exactly.
    if args.a2_minus is None:
        args.a2_minus = args.a2_plus if args.symmetric else 1

    print(f"Generating STDP LUTs:")
    print(f"  W_BITS={args.w_bits}  TRACE_BITS={args.trace_bits}  TRIPLET_EN={args.triplet_en}")
    print(f"  A2_PLUS={args.a2_plus}  A2_MINUS={args.a2_minus}  A3_PLUS={args.a3_plus}  A3_MINUS={args.a3_minus}")
    print(f"  DW_SCALE={args.trace_bits - 2}  W_MAX={(1 << args.w_bits) - 1}")

    pot_lut, dep_lut, num_entries = generate_luts(args)
    print(f"  Generated {num_entries} entries per LUT")

    # Self-test
    if not args.no_test:
        errors = self_test(pot_lut, dep_lut, args)
        if errors == 0:
            print(f"  Self-test: PASS (all {num_entries * 2} entries verified)")
        else:
            print(f"  Self-test: FAIL ({errors} mismatches)")
            return 1

    # Write output files
    os.makedirs(args.output_dir, exist_ok=True)

    pot_path = os.path.join(args.output_dir, "stdp_pot.mem")
    dep_path = os.path.join(args.output_dir, "stdp_dep.mem")
    vh_path = os.path.join(args.output_dir, "stdp_lut_data.vh")

    write_mem_file(pot_path, pot_lut, args.w_bits)
    write_mem_file(dep_path, dep_lut, args.w_bits)
    write_verilog_header(vh_path, pot_lut, dep_lut, args.w_bits)

    print(f"  Wrote: {pot_path} ({num_entries} entries)")
    print(f"  Wrote: {dep_path} ({num_entries} entries)")
    print(f"  Wrote: {vh_path} (synthesis include)")

    return 0


if __name__ == "__main__":
    exit(main())
